USE my_homework;

INSERT INTO Top5_Departure_Delay
SELECT IATA_CODE, AIRLINE, DEPARTURE_DELAY_AVG FROM
(
SELECT a.IATA_CODE, a.AIRLINE, NVL(AVG(f.DEPARTURE_DELAY), 0) AS DEPARTURE_DELAY_AVG 
FROM Airlines a LEFT JOIN Flights f ON (a.IATA_CODE = f.AIRLINE)
GROUP BY a.IATA_CODE, a.AIRLINE 
) s
ORDER BY DEPARTURE_DELAY_AVG DESC
LIMIT 5;